version: 2
general:
  branches:
    only:
      - development
jobs:
  build:
    docker: 
      - image: node:8.9.4
    working_directory: /home/ubuntu/neoblog
    steps:
      - checkout
      - run: cd /home/ubuntu/neoblog/packages/client
      - run: yarn install
      - run: yarn test
      - run: yarn build
    deployment:
      development:
        branch: development
        commands:
          - surge --project /home/ubuntu/neoblog/packages/client/build domain testnet.neoblog.io