version: 2
general:
  branches:
    only:
      - development
jobs:
  build:
    docker: 
      - image: node:8.9.4
    working_directory: /home/ubuntu/neoblog
    steps:
      - checkout
      - run: yarn install
      - run: cd /home/ubuntu/neoblog/packages/client && yarn install
      - run: yarn test
      - run: cd /home/ubuntu/neoblog/packages/client && yarn test
      - run: cd /home/ubuntu/neoblog/packages/client && yarn build
      - run: cp /home/ubuntu/neoblog/packages/client/build/index.html /home/ubuntu/neoblog/packages/client/build/200.html
      - run: npx surge --project /home/ubuntu/neoblog/packages/client/build domain testnet.neoblog.io